GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/2

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "John Doe",
    "subscribedToChannel": "Codevolution"
}

### 

PATCH http://localhost:3000/subscribers/2

{
    "subscribedToChannel": "Codevolution"
}    

###

DELETE http://localhost:3000/subscribers/2   
